package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model thermosonicBonder.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class BonderModel {
    public static final String[] PARTS = {"peg1", "peg2", "plug", "base", "viewer", "aimpoint", "laser", "arm2", "arm1"};

    private BonderModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("peg1", CubeListBuilder.create().texOffs(0, 22).addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(-8F, 0F, -8F));
        root.addOrReplaceChild("peg2", CubeListBuilder.create().texOffs(0, 22).addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(6F, 0F, -8F));
        root.addOrReplaceChild("plug", CubeListBuilder.create().texOffs(42, 0).addBox(0F, 0F, 0F, 6F, 5F, 5F), PartPose.offset(-3F, -2F, 3F));
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(8, 11).addBox(0F, 0F, 0F, 14F, 7F, 14F), PartPose.offset(-7F, 1F, -7F));
        root.addOrReplaceChild("viewer", CubeListBuilder.create().texOffs(0, 0).addBox(-1F, 0F, -1F, 8F, 1F, 7F), PartPose.offsetAndRotation(-3F, -3F, -6F, 0.7854F, 0F, 0F));
        root.addOrReplaceChild("aimpoint", CubeListBuilder.create().texOffs(30, 0).addBox(-1F, 0F, 0F, 2F, 3F, 2F), PartPose.offsetAndRotation(0F, 1F, 0F, 0.7854F, 0F, 0F));
        root.addOrReplaceChild("laser", CubeListBuilder.create().texOffs(38, 0).addBox(-0.5F, 0F, -0.5F, 1F, 6F, 1F), PartPose.offsetAndRotation(0F, -4F, -3.5F, 0.7854F, 0F, 0F));
        root.addOrReplaceChild("arm2", CubeListBuilder.create().texOffs(0, 10).addBox(0F, 0F, 0F, 1F, 9F, 3F), PartPose.offsetAndRotation(2F, -3F, -4.5F, 0.7854F, 0F, 0F));
        root.addOrReplaceChild("arm1", CubeListBuilder.create().texOffs(0, 10).addBox(0F, 0F, 0F, 1F, 9F, 3F), PartPose.offsetAndRotation(-3F, -3F, -4.5F, 0.7854F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
