package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model clayFurnace.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class ClayFurnaceModel {
    public static final String[] PARTS = {"base1", "base2", "base3", "base4", "top1", "top2", "top3", "top4", "post1", "post2", "post3", "post4", "moltenblockshell", "moltenblock"};

    private ClayFurnaceModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("base1", CubeListBuilder.create().texOffs(0, 81).addBox(-13.5F, 0F, -5.5F, 27F, 16F, 11F), PartPose.offsetAndRotation(0F, -8F, 0F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("base2", CubeListBuilder.create().texOffs(0, 27).addBox(-13.5F, 0F, -5.5F, 27F, 16F, 11F), PartPose.offsetAndRotation(0F, -8F, 0F, 0F, -0.7854F, 0F));
        root.addOrReplaceChild("base3", CubeListBuilder.create().texOffs(0, 54).addBox(0F, 0F, 0F, 27F, 16F, 11F), PartPose.offset(-13.5F, -8F, -5.5F));
        root.addOrReplaceChild("base4", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 27F, 16F, 11F), PartPose.offsetAndRotation(-5.5F, -8F, 13.5F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("top1", CubeListBuilder.create().texOffs(76, 0).addBox(0F, 0F, 0F, 12F, 3F, 10F), PartPose.offsetAndRotation(6F, -8F, 13F, 0.7854F, 3.1416F, 0F));
        root.addOrReplaceChild("top2", CubeListBuilder.create().texOffs(76, 13).addBox(0F, 0F, 0F, 12F, 3F, 10F), PartPose.offsetAndRotation(-6F, -8F, -13F, 0.7854F, 0F, 0F));
        root.addOrReplaceChild("top3", CubeListBuilder.create().texOffs(76, 26).addBox(0F, 0F, 0F, 12F, 3F, 10F), PartPose.offsetAndRotation(13F, -8F, -6F, 0.7854F, -1.5708F, 0F));
        root.addOrReplaceChild("top4", CubeListBuilder.create().texOffs(76, 39).addBox(0F, 0F, 0F, 12F, 3F, 10F), PartPose.offsetAndRotation(-13F, -8F, 6F, 0.7854F, 1.5708F, 0F));
        root.addOrReplaceChild("post1", CubeListBuilder.create().texOffs(76, 52).addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(5F, -16F, 5F));
        root.addOrReplaceChild("post2", CubeListBuilder.create().texOffs(84, 52).addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(5F, -16F, -7F));
        root.addOrReplaceChild("post3", CubeListBuilder.create().texOffs(92, 52).addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(-7F, -16F, 5F));
        root.addOrReplaceChild("post4", CubeListBuilder.create().texOffs(100, 52).addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(-7F, -16F, -7F));
        root.addOrReplaceChild("moltenblockshell", CubeListBuilder.create().texOffs(120, 32).addBox(0F, 0F, 0F, 17F, 17F, 17F), PartPose.offset(-8.5F, -9F, -8.5F));
        root.addOrReplaceChild("moltenblock", CubeListBuilder.create().texOffs(120, 0).addBox(0F, 0F, 0F, 16F, 16F, 16F), PartPose.offset(-8F, -8F, -8F));
        return LayerDefinition.create(mesh, 256, 128);
    }
}
