package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model cncMachine_Base.mad (+27 more). Generated by scripts/techne2java.py; do not edit by hand. */
public final class CncMachineModel {
    public static final String[] PARTS = {"armtop", "armbottom", "toppanel", "front", "railright", "railleft", "baseplate", "basemiddle", "base", "railtop", "railback", "screen_monitor", "press0_press0", "press1_press1", "press2_press2", "press3_press3", "comp0_compressedblock0", "comp1_compressedblock1", "comp2_compressedblock2", "comp3_compressedblock3", "cut0_cutblock0", "cut1_cutblock1", "cut2_cutblock2", "cut3_cutblock3", "cut4_cutblock4", "cut5_cutblock5", "cut6_cutblock6", "cut7_cutblock7", "cut8_cutblock8", "water0_water0", "water1_water1", "water2_water2", "water3_water3", "water4_water4", "water5_water5", "water6_water6", "water7_water7", "water8_water8"};

    private CncMachineModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("armtop", CubeListBuilder.create().texOffs(96, 7).addBox(0F, 0F, 0F, 3F, 1F, 13F), PartPose.offset(-1.5F, -24F, -6F));
        root.addOrReplaceChild("armbottom", CubeListBuilder.create().texOffs(56, 0).addBox(0F, 0F, 0F, 4F, 1F, 3F), PartPose.offset(-2F, -16F, -5F));
        root.addOrReplaceChild("toppanel", CubeListBuilder.create().texOffs(57, 17).addBox(0F, 0F, 0F, 2F, 8F, 5F), PartPose.offset(-1F, -23F, 2F));
        root.addOrReplaceChild("front", CubeListBuilder.create().texOffs(33, 65).addBox(0F, 0F, 0F, 4F, 4F, 1F), PartPose.offsetAndRotation(2F, -2F, -7F, 0F, 3.1416F, 0F));
        root.addOrReplaceChild("railright", CubeListBuilder.create().texOffs(11, 65).addBox(0F, 0F, 0F, 4F, 18F, 1F), PartPose.offsetAndRotation(-8F, -15F, 2F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("railleft", CubeListBuilder.create().texOffs(22, 65).addBox(0F, 0F, 0F, 4F, 18F, 1F), PartPose.offsetAndRotation(8F, -15F, -2F, 0F, -1.5708F, 0F));
        root.addOrReplaceChild("baseplate", CubeListBuilder.create().texOffs(186, 0).addBox(0F, 0F, 0F, 14F, 2F, 14F), PartPose.offset(-7F, 1F, -7F));
        root.addOrReplaceChild("basemiddle", CubeListBuilder.create().texOffs(186, 17).addBox(0F, 0F, 0F, 8F, 4F, 8F), PartPose.offset(-4F, 3F, -4F));
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(186, 30).addBox(0F, 0F, 0F, 12F, 1F, 12F), PartPose.offset(-6F, 7F, -6F));
        root.addOrReplaceChild("railtop", CubeListBuilder.create().texOffs(88, 0).addBox(0F, 0F, 0F, 16F, 2F, 4F), PartPose.offset(-8F, -17F, -2F));
        root.addOrReplaceChild("railback", CubeListBuilder.create().texOffs(0, 65).addBox(0F, 0F, 0F, 4F, 27F, 1F), PartPose.offset(-2F, -24F, 7F));
        root.addOrReplaceChild("screen_monitor", CubeListBuilder.create().texOffs(57, 6).addBox(0F, 0F, 0F, 16F, 9F, 1F), PartPose.offsetAndRotation(-8F, -24F, -7F, 0.1745F, 0F, 0F));
        root.addOrReplaceChild("press0_press0", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 14F, 2F, 14F), PartPose.offset(-7F, -15F, -7F));
        root.addOrReplaceChild("press1_press1", CubeListBuilder.create().texOffs(0, 16).addBox(-15F, 0F, 0F, 14F, 2F, 14F), PartPose.offset(8F, -11F, -7F));
        root.addOrReplaceChild("press2_press2", CubeListBuilder.create().texOffs(0, 32).addBox(-15F, 0F, 0F, 14F, 2F, 14F), PartPose.offset(8F, -7F, -7F));
        root.addOrReplaceChild("press3_press3", CubeListBuilder.create().texOffs(0, 48).addBox(-15F, 0F, 0F, 14F, 2F, 14F), PartPose.offset(8F, -3F, -7F));
        root.addOrReplaceChild("comp0_compressedblock0", CubeListBuilder.create().texOffs(129, 0).addBox(-15F, 0F, 0F, 14F, 14F, 14F), PartPose.offset(8F, -13F, -7F));
        root.addOrReplaceChild("comp1_compressedblock1", CubeListBuilder.create().texOffs(129, 29).addBox(-15F, 0F, 0F, 14F, 10F, 14F), PartPose.offset(8F, -9F, -7F));
        root.addOrReplaceChild("comp2_compressedblock2", CubeListBuilder.create().texOffs(129, 54).addBox(-15F, 0F, 0F, 14F, 6F, 14F), PartPose.offset(8F, -5F, -7F));
        root.addOrReplaceChild("comp3_compressedblock3", CubeListBuilder.create().texOffs(129, 75).addBox(-15F, 0F, 0F, 14F, 2F, 14F), PartPose.offset(8F, -1F, -7F));
        root.addOrReplaceChild("cut0_cutblock0", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(-6F, 0F, 2F));
        root.addOrReplaceChild("cut1_cutblock1", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(-2F, 0F, 2F));
        root.addOrReplaceChild("cut2_cutblock2", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(2F, 0F, 2F));
        root.addOrReplaceChild("cut3_cutblock3", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(2F, 0F, -2F));
        root.addOrReplaceChild("cut4_cutblock4", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(-2F, 0F, -2F));
        root.addOrReplaceChild("cut5_cutblock5", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(-6F, 0F, -2F));
        root.addOrReplaceChild("cut6_cutblock6", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(-6F, 0F, -6F));
        root.addOrReplaceChild("cut7_cutblock7", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(-2F, 0F, -6F));
        root.addOrReplaceChild("cut8_cutblock8", CubeListBuilder.create().texOffs(72, 65).addBox(0F, 0F, 0F, 4F, 1F, 4F), PartPose.offset(2F, 0F, -6F));
        root.addOrReplaceChild("water0_water0", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(-5.5F, -13F, 2.5F));
        root.addOrReplaceChild("water1_water1", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(-1.5F, -13F, 2.5F));
        root.addOrReplaceChild("water2_water2", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(2.5F, -13F, 2.5F));
        root.addOrReplaceChild("water3_water3", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(-5.5F, -13F, -1.5F));
        root.addOrReplaceChild("water4_water4", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(-1.5F, -13F, -1.5F));
        root.addOrReplaceChild("water5_water5", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(2.5F, -13F, -1.5F));
        root.addOrReplaceChild("water6_water6", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(-5.5F, -13F, -5.5F));
        root.addOrReplaceChild("water7_water7", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(-1.5F, -13F, -5.5F));
        root.addOrReplaceChild("water8_water8", CubeListBuilder.create().texOffs(0, 112).addBox(0F, 0F, 0F, 3F, 13F, 3F), PartPose.offset(2.5F, -13F, -5.5F));
        return LayerDefinition.create(mesh, 256, 128);
    }
}
