package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model cryoTube.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class CryotubeModel {
    public static final String[] PARTS = {"top", "base", "tube1", "tube2", "tube3", "tube4"};

    private CryotubeModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, -16F, 16F, 9F, 16F), PartPose.offset(-8F, -40F, 8F));
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(64, 42).addBox(0F, -2F, 0F, 16F, 2F, 16F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("tube1", CubeListBuilder.create().texOffs(0, 15).addBox(0F, -38F, 0F, 14F, 38F, 11F), PartPose.offset(-7F, 6F, -4F));
        root.addOrReplaceChild("tube2", CubeListBuilder.create().texOffs(74, -1).addBox(0F, 0F, 0F, 4F, 38F, 4F), PartPose.offsetAndRotation(-7F, -32F, -4F, 0F, 0.8011F, 0F));
        root.addOrReplaceChild("tube3", CubeListBuilder.create().texOffs(90, -1).addBox(0F, 0F, 0F, 4F, 38F, 4F), PartPose.offsetAndRotation(1.3F, -32F, -3.95F, 0F, 0.8011F, 0F));
        root.addOrReplaceChild("tube4", CubeListBuilder.create().texOffs(106, 0).addBox(0F, 0F, 0F, 8F, 38F, 3F), PartPose.offset(-4F, -32F, -7F));
        return LayerDefinition.create(mesh, 128, 64);
    }
}
