package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model dnaExtractor.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class DnaExtractorModel {
    public static final String[] PARTS = {"foot4", "foot2", "foot3", "top", "foot1", "middle", "base"};

    private DnaExtractorModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("foot4", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(6F, 7F, 6F));
        root.addOrReplaceChild("foot2", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-7F, 7F, -7F));
        root.addOrReplaceChild("foot3", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-7F, 7F, 6F));
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(0, 3).addBox(0F, 0F, 0F, 16F, 9F, 16F), PartPose.offset(-8F, -7F, -8F));
        root.addOrReplaceChild("foot1", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(6F, 7F, -7F));
        root.addOrReplaceChild("middle", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 4F, 15F), PartPose.offset(-8F, 2F, -7F));
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(0, 13).addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 6F, -8F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
