package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model dataDuplicator.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class DuplicatorModel {
    public static final String[] PARTS = {"leg1", "leg2", "leg3", "leg4", "base", "top", "middle", "leftdisc", "rightdisc", "reader", "leftpin", "rightpin", "bottomtape", "righttape", "lefttape", "rightdiscpin", "leftdiscpin"};

    private DuplicatorModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("leg1", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-8F, 7F, -8F));
        root.addOrReplaceChild("leg2", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-8F, 7F, 7F));
        root.addOrReplaceChild("leg3", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(7F, 7F, 7F));
        root.addOrReplaceChild("leg4", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(7F, 7F, -8F));
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(0, 3).addBox(0F, 0F, 0F, 16F, 2F, 16F), PartPose.offset(-8F, 5F, -8F));
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(0, 3).addBox(0F, 0F, 0F, 16F, 2F, 16F), PartPose.offset(-8F, -8F, -8F));
        root.addOrReplaceChild("middle", CubeListBuilder.create().texOffs(2, 7).addBox(0F, 0F, 0F, 16F, 11F, 14F), PartPose.offset(-8F, -6F, -6F));
        root.addOrReplaceChild("leftdisc", CubeListBuilder.create().texOffs(50, 7).addBox(0F, 0F, 0F, 6F, 6F, 1F), PartPose.offset(-7F, -5F, -7F));
        root.addOrReplaceChild("rightdisc", CubeListBuilder.create().texOffs(50, 0).addBox(0F, 0F, 0F, 6F, 6F, 1F), PartPose.offset(1F, -5F, -7F));
        root.addOrReplaceChild("reader", CubeListBuilder.create().texOffs(4, 0).addBox(0F, 0F, 0F, 4F, 1F, 1F), PartPose.offset(-2F, 3F, -7F));
        root.addOrReplaceChild("leftpin", CubeListBuilder.create().texOffs(44, 0).addBox(0F, 0F, 0F, 1F, 1F, 2F), PartPose.offset(-7F, 3F, -8F));
        root.addOrReplaceChild("rightpin", CubeListBuilder.create().texOffs(38, 0).addBox(0F, 0F, 0F, 1F, 1F, 2F), PartPose.offset(6F, 3F, -8F));
        root.addOrReplaceChild("bottomtape", CubeListBuilder.create().texOffs(0, 2).addBox(0F, 0F, 0F, 14F, 0F, 1F), PartPose.offset(-7F, 4F, -7F));
        root.addOrReplaceChild("righttape", CubeListBuilder.create().texOffs(0, 25).addBox(0F, 0F, 0F, 0F, 3F, 1F), PartPose.offset(7F, 1F, -7F));
        root.addOrReplaceChild("lefttape", CubeListBuilder.create().texOffs(0, 21).addBox(0F, 0F, 0F, 0F, 3F, 1F), PartPose.offset(-7F, 1F, -7F));
        root.addOrReplaceChild("rightdiscpin", CubeListBuilder.create().texOffs(34, 0).addBox(-0.5F, -0.5F, 0.5333F, 1F, 1F, 1F), PartPose.offset(4F, -2F, -8F));
        root.addOrReplaceChild("leftdiscpin", CubeListBuilder.create().texOffs(30, 0).addBox(-0.5F, -0.5F, 0.5F, 1F, 1F, 1F), PartPose.offset(-4F, -2F, -8F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
