package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model cryoFreezer.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class FreezerModel {
    public static final String[] PARTS = {"base", "leg1", "leg2", "leg3", "leg4"};

    private FreezerModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 15F, 16F), PartPose.offset(-8F, -8F, -8F));
        root.addOrReplaceChild("leg1", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-8F, 7F, -8F));
        root.addOrReplaceChild("leg2", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(7F, 7F, 7F));
        root.addOrReplaceChild("leg3", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(7F, 7F, -8F));
        root.addOrReplaceChild("leg4", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-8F, 7F, 7F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
