package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model genomeIncubator.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class IncubatorModel {
    public static final String[] PARTS = {"foot4", "foot2", "foot3", "top", "foot1", "leftright", "bottom", "frontright", "left", "egg", "glass"};

    private IncubatorModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("foot4", CubeListBuilder.create().texOffs(12, 22).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(6F, 7F, 6F));
        root.addOrReplaceChild("foot2", CubeListBuilder.create().texOffs(12, 22).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-7F, 7F, -7F));
        root.addOrReplaceChild("foot3", CubeListBuilder.create().texOffs(12, 22).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-7F, 7F, 6F));
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 4F, 16F), PartPose.offset(-8F, -7F, -8F));
        root.addOrReplaceChild("foot1", CubeListBuilder.create().texOffs(12, 22).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(6F, 7F, -7F));
        root.addOrReplaceChild("leftright", CubeListBuilder.create().texOffs(0, 20).addBox(0F, 0F, 0F, 3F, 9F, 3F), PartPose.offset(-8F, -3F, -8F));
        root.addOrReplaceChild("bottom", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 6F, -8F));
        root.addOrReplaceChild("frontright", CubeListBuilder.create().texOffs(0, 20).addBox(0F, 0F, 0F, 3F, 9F, 3F), PartPose.offset(5F, -3F, -8F));
        root.addOrReplaceChild("left", CubeListBuilder.create().texOffs(3, 0).addBox(0F, 0F, 0F, 16F, 9F, 13F), PartPose.offset(-8F, -3F, -5F));
        root.addOrReplaceChild("egg", CubeListBuilder.create().texOffs(12, 24).addBox(0F, 0F, 0F, 8F, 7F, 1F), PartPose.offset(-4F, -2F, -6F));
        root.addOrReplaceChild("glass", CubeListBuilder.create().texOffs(42, 22).addBox(0F, 0F, 0F, 10F, 9F, 1F), PartPose.offset(-5F, -3F, -8F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
