package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model magLoader.mad (+13 more). Generated by scripts/techne2java.py; do not edit by hand. */
public final class MagazineLoaderModel {
    public static final String[] PARTS = {"base", "baseleft", "baseright", "baseclampright", "baseclampleft", "clampleft", "clampright", "clampboltleft", "clampboltright", "clampholderleft", "clampholderright", "clamparmbottomleft", "clamparmbottomright", "clamparmleft", "clamparmright", "funneltop", "funnelmid", "funnelbottom", "shelftop", "shelfright", "shelfleft", "rim0", "rim1", "rim2", "rim3", "push0", "plugleft", "plugarm", "plugright", "plugback", "b0_bullet0", "b1_bullet1", "b2_bullet2", "b3_bullet3", "b4_bullet4", "p0_push0", "p1_push1", "p2_push2", "p3_push3", "p4_push4", "p5_push5", "mag_magazine", "magbase_magazinebase"};

    private MagazineLoaderModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(0, 97).addBox(0F, 0F, 0F, 28F, 3F, 28F), PartPose.offset(-14F, 5F, -14F));
        root.addOrReplaceChild("baseleft", CubeListBuilder.create().texOffs(192, 28).addBox(0F, 0F, 0F, 8F, 3F, 24F), PartPose.offset(-12F, 2F, -12F));
        root.addOrReplaceChild("baseright", CubeListBuilder.create().texOffs(192, 55).addBox(0F, 0F, 0F, 8F, 3F, 24F), PartPose.offset(4F, 2F, -12F));
        root.addOrReplaceChild("baseclampright", CubeListBuilder.create().texOffs(152, 102).addBox(0F, 0F, 0F, 4F, 5F, 18F), PartPose.offset(3F, -3F, -9F));
        root.addOrReplaceChild("baseclampleft", CubeListBuilder.create().texOffs(100, 102).addBox(0F, 0F, 0F, 4F, 5F, 18F), PartPose.offset(-7F, -3F, -9F));
        root.addOrReplaceChild("clampleft", CubeListBuilder.create().texOffs(12, 50).addBox(0F, 0F, 0F, 2F, 3F, 4F), PartPose.offset(2F, -17F, -2F));
        root.addOrReplaceChild("clampright", CubeListBuilder.create().texOffs(0, 50).addBox(0F, 0F, 0F, 2F, 3F, 4F), PartPose.offset(-4F, -17F, -2F));
        root.addOrReplaceChild("clampboltleft", CubeListBuilder.create().texOffs(10, 22).addBox(0F, 0F, 0F, 1F, 1F, 4F), PartPose.offset(-14F, 0F, -2F));
        root.addOrReplaceChild("clampboltright", CubeListBuilder.create().texOffs(0, 22).addBox(0F, 0F, 0F, 1F, 1F, 4F), PartPose.offset(13F, 0F, -2F));
        root.addOrReplaceChild("clampholderleft", CubeListBuilder.create().texOffs(0, 61).addBox(0F, 0F, 0F, 8F, 3F, 3F), PartPose.offset(-15F, -1F, -1.5F));
        root.addOrReplaceChild("clampholderright", CubeListBuilder.create().texOffs(20, 61).addBox(0F, 0F, 0F, 8F, 3F, 3F), PartPose.offset(7F, -1F, -1.5F));
        root.addOrReplaceChild("clamparmbottomleft", CubeListBuilder.create().texOffs(48, 48).addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-14F, -16F, -1F));
        root.addOrReplaceChild("clamparmbottomright", CubeListBuilder.create().texOffs(48, 48).addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(12F, -16F, -1F));
        root.addOrReplaceChild("clamparmleft", CubeListBuilder.create().texOffs(0, 57).addBox(0F, 0F, 0F, 8F, 2F, 2F), PartPose.offset(-12F, -16F, -1F));
        root.addOrReplaceChild("clamparmright", CubeListBuilder.create().texOffs(20, 57).addBox(0F, 0F, 0F, 8F, 2F, 2F), PartPose.offset(4F, -16F, -1F));
        root.addOrReplaceChild("funneltop", CubeListBuilder.create().texOffs(0, 67).addBox(0F, 0F, 0F, 26F, 4F, 26F), PartPose.offset(-13F, -54F, -13F));
        root.addOrReplaceChild("funnelmid", CubeListBuilder.create().texOffs(120, 70).addBox(0F, 0F, 0F, 20F, 4F, 20F), PartPose.offset(-10F, -50F, -10F));
        root.addOrReplaceChild("funnelbottom", CubeListBuilder.create().texOffs(112, 56).addBox(0F, 0F, 0F, 11F, 5F, 9F), PartPose.offset(-5.5F, -46F, -4.5F));
        root.addOrReplaceChild("shelftop", CubeListBuilder.create().texOffs(56, 57).addBox(0F, 0F, 0F, 9F, 2F, 8F), PartPose.offset(-4.5F, -41F, -4F));
        root.addOrReplaceChild("shelfright", CubeListBuilder.create().texOffs(172, 40).addBox(0F, 0F, 0F, 2F, 22F, 8F), PartPose.offset(2F, -39F, -4F));
        root.addOrReplaceChild("shelfleft", CubeListBuilder.create().texOffs(152, 40).addBox(0F, 0F, 0F, 2F, 22F, 8F), PartPose.offset(-4F, -39F, -4F));
        root.addOrReplaceChild("rim0", CubeListBuilder.create().texOffs(112, 94).addBox(0F, 0F, 0F, 4F, 2F, 32F), PartPose.offset(12F, -56F, -16F));
        root.addOrReplaceChild("rim1", CubeListBuilder.create().texOffs(200, 82).addBox(0F, 0F, 0F, 24F, 2F, 4F), PartPose.offset(-12F, -56F, 12F));
        root.addOrReplaceChild("rim2", CubeListBuilder.create().texOffs(184, 94).addBox(0F, 0F, 0F, 4F, 2F, 32F), PartPose.offset(-16F, -56F, -16F));
        root.addOrReplaceChild("rim3", CubeListBuilder.create().texOffs(200, 88).addBox(0F, 0F, 0F, 24F, 2F, 4F), PartPose.offset(-12F, -56F, -16F));
        root.addOrReplaceChild("push0", CubeListBuilder.create().texOffs(56, 24).addBox(0F, 0F, 0F, 4F, 1F, 7F), PartPose.offset(-2F, -39F, -3.5F));
        root.addOrReplaceChild("plugleft", CubeListBuilder.create().texOffs(3, 103).addBox(0F, 0F, 0F, 2F, 8F, 8F), PartPose.offset(-15F, -11.5F, -4F));
        root.addOrReplaceChild("plugarm", CubeListBuilder.create().texOffs(48, 48).addBox(0F, 0F, 0F, 2F, 10F, 2F), PartPose.offset(-1F, -5F, 12F));
        root.addOrReplaceChild("plugright", CubeListBuilder.create().texOffs(3, 103).addBox(0F, 0F, 0F, 2F, 8F, 8F), PartPose.offsetAndRotation(15F, -11.5F, 4F, 0F, 3.1416F, 0F));
        root.addOrReplaceChild("plugback", CubeListBuilder.create().texOffs(3, 103).addBox(0F, 0F, 0F, 2F, 8F, 8F), PartPose.offsetAndRotation(-4F, -11.5F, 15F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("b0_bullet0", CubeListBuilder.create().texOffs(0, 11).addBox(0F, 0F, 0F, 4F, 4F, 6F), PartPose.offset(-2F, -38F, -3F));
        root.addOrReplaceChild("b1_bullet1", CubeListBuilder.create().texOffs(22, 11).addBox(0F, 0F, 0F, 4F, 4F, 6F), PartPose.offset(-2F, -34F, -3F));
        root.addOrReplaceChild("b2_bullet2", CubeListBuilder.create().texOffs(44, 11).addBox(0F, 0F, 0F, 4F, 4F, 6F), PartPose.offset(-2F, -30F, -3F));
        root.addOrReplaceChild("b3_bullet3", CubeListBuilder.create().texOffs(66, 11).addBox(0F, 0F, 0F, 4F, 4F, 6F), PartPose.offset(-2F, -26F, -3F));
        root.addOrReplaceChild("b4_bullet4", CubeListBuilder.create().texOffs(88, 11).addBox(0F, 0F, 0F, 4F, 4F, 6F), PartPose.offset(-2F, -22F, -3F));
        root.addOrReplaceChild("p0_push0", CubeListBuilder.create().texOffs(56, 24).addBox(0F, 0F, 0F, 4F, 1F, 7F), PartPose.offset(-2F, -39F, -3.5F));
        root.addOrReplaceChild("p1_push1", CubeListBuilder.create().texOffs(80, 24).addBox(0F, 0F, 0F, 4F, 5F, 7F), PartPose.offset(-2F, -39F, -3.5F));
        root.addOrReplaceChild("p2_push2", CubeListBuilder.create().texOffs(104, 24).addBox(0F, 0F, 0F, 4F, 9F, 7F), PartPose.offset(-2F, -39F, -3.5F));
        root.addOrReplaceChild("p3_push3", CubeListBuilder.create().texOffs(128, 2).addBox(0F, 0F, 0F, 4F, 13F, 7F), PartPose.offset(-2F, -39F, -3.5F));
        root.addOrReplaceChild("p4_push4", CubeListBuilder.create().texOffs(152, 14).addBox(0F, 0F, 0F, 4F, 17F, 7F), PartPose.offset(-2F, -39F, -3.5F));
        root.addOrReplaceChild("p5_push5", CubeListBuilder.create().texOffs(128, 24).addBox(0F, 0F, 0F, 4F, 21F, 7F), PartPose.offset(-2F, -39F, -3.5F));
        root.addOrReplaceChild("mag_magazine", CubeListBuilder.create().texOffs(34, 24).addBox(0F, 0F, 0F, 4F, 18F, 6F), PartPose.offset(-2F, -18F, -3F));
        root.addOrReplaceChild("magbase_magazinebase", CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 6F, 4F, 10F), PartPose.offset(-3F, 0F, -5F));
        return LayerDefinition.create(mesh, 256, 128);
    }
}
