package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model computerMainframe.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class MainframeModel {
    public static final String[] PARTS = {"bottom", "shell", "top", "glass"};

    private MainframeModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("bottom", CubeListBuilder.create().texOffs(8, 17).addBox(0F, 0F, 0F, 14F, 1F, 14F), PartPose.offset(-7F, 7F, -7F));
        root.addOrReplaceChild("shell", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 15F, 16F), PartPose.offset(-8F, -8F, -8F));
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(8, 17).addBox(0F, 0F, 0F, 14F, 1F, 14F), PartPose.offsetAndRotation(-7F, -8F, 7F, 3.1625F, 0F, 0F));
        root.addOrReplaceChild("glass", CubeListBuilder.create().texOffs(48, 0).addBox(0F, 0F, 0F, 14F, 13F, 1F), PartPose.offset(-7F, -7F, -8.1F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
