package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model meatCube.mad (+14 more). Generated by scripts/techne2java.py; do not edit by hand. */
public final class MeatCubeModel {
    public static final String[] PARTS = {"bone", "meat0", "piece1_meat1", "piece2_meat2", "piece3_meat3", "piece4_meat4", "piece5_meat5", "piece6_meat6", "piece7_meat7", "piece8_meat8", "piece9_meat9", "piece10_meat10", "piece11_meat11", "piece12_meat12", "piece13_meat13", "piece14_meat14"};

    private MeatCubeModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("bone", CubeListBuilder.create().texOffs(64, 12).addBox(0F, 0F, 0F, 4F, 16F, 4F), PartPose.offset(-2F, -8F, -2F));
        root.addOrReplaceChild("meat0", CubeListBuilder.create().texOffs(0, 15).addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 7F, -8F));
        root.addOrReplaceChild("piece1_meat1", CubeListBuilder.create().texOffs(0, 14).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 22F, 0F));
        root.addOrReplaceChild("piece2_meat2", CubeListBuilder.create().texOffs(0, 13).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 21F, 0F));
        root.addOrReplaceChild("piece3_meat3", CubeListBuilder.create().texOffs(0, 12).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 20F, 0F));
        root.addOrReplaceChild("piece4_meat4", CubeListBuilder.create().texOffs(0, 11).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 19F, 0F));
        root.addOrReplaceChild("piece5_meat5", CubeListBuilder.create().texOffs(0, 10).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 18F, 0F));
        root.addOrReplaceChild("piece6_meat6", CubeListBuilder.create().texOffs(0, 9).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 17F, 0F));
        root.addOrReplaceChild("piece7_meat7", CubeListBuilder.create().texOffs(0, 8).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 16F, 0F));
        root.addOrReplaceChild("piece8_meat8", CubeListBuilder.create().texOffs(0, 7).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("piece9_meat9", CubeListBuilder.create().texOffs(0, 6).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 14F, 0F));
        root.addOrReplaceChild("piece10_meat10", CubeListBuilder.create().texOffs(0, 5).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 13F, 0F));
        root.addOrReplaceChild("piece11_meat11", CubeListBuilder.create().texOffs(0, 4).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 12F, 0F));
        root.addOrReplaceChild("piece12_meat12", CubeListBuilder.create().texOffs(0, 3).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 11F, 0F));
        root.addOrReplaceChild("piece13_meat13", CubeListBuilder.create().texOffs(0, 3).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("piece14_meat14", CubeListBuilder.create().texOffs(0, 2).addBox(-8F, -16F, -8F, 16F, 1F, 16F), PartPose.offset(0F, 9F, 0F));
        return LayerDefinition.create(mesh, 128, 32);
    }
}
