package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model pulseRifleBullet.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class PulseRifleRoundModel {
    public static final String[] PARTS = {"tip", "head", "shaft", "knot"};

    private PulseRifleRoundModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("tip", CubeListBuilder.create().texOffs(14, 12).addBox(-3F, -3F, 0F, 2F, 2F, 2F), PartPose.offset(2F, 2F, 0F));
        root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 12).addBox(-3F, -3F, 0F, 3F, 3F, 4F), PartPose.offset(1.5F, 1.5F, 2F));
        root.addOrReplaceChild("shaft", CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -3F, 0F, 4F, 4F, 8F), PartPose.offset(2F, 1F, 6F));
        root.addOrReplaceChild("knot", CubeListBuilder.create().texOffs(24, 8).addBox(-2.5F, -2.5F, 0F, 3F, 3F, 1F), PartPose.offset(1F, 1F, 14F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
