package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model pulseRifle.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class PulseRifleModel {
    public static final String[] PARTS = {"bolt", "boltback", "boltbody", "magazineguard", "magazineguardtrim", "magazinetop", "magazinetoptrim", "magazinemid", "bodytopfront", "bodytoprear", "bodymidtrim", "bodymidangletrim", "bodylow", "bodylowtrim", "bodystocktrim", "bodyfronttrim", "pumpfrontback", "pumpbackback", "handle", "handleanglefront", "handlefronttrim", "handlerear", "sightright", "sightleft", "barrelspacer", "barrelholderrear", "barrelholdermid", "barrelholderfront", "grenadelauncher", "grenadebarrel", "grateright", "grateleft", "stock", "trigger", "griptrim", "grip", "magazinelow", "pumpfront", "pumpback", "barrel", "counter"};

    private PulseRifleModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("bolt", CubeListBuilder.create().texOffs(265, 245).addBox(-10F, 0F, 0F, 20F, 5F, 5F), PartPose.offset(0F, -7F, 70F));
        root.addOrReplaceChild("boltback", CubeListBuilder.create().texOffs(265, 245).addBox(-10F, 0F, 0F, 20F, 5F, 5F), PartPose.offset(0F, -7F, 31F));
        root.addOrReplaceChild("boltbody", CubeListBuilder.create().texOffs(201, 136).addBox(-4.5F, 0F, 0F, 9F, 9F, 74F), PartPose.offset(0F, -9F, 8F));
        root.addOrReplaceChild("magazineguard", CubeListBuilder.create().texOffs(142, 181).addBox(-4F, -37F, 0F, 8F, 37F, 9F), PartPose.offsetAndRotation(0F, 59F, 15F, 0.7156F, 0F, 0F));
        root.addOrReplaceChild("magazineguardtrim", CubeListBuilder.create().texOffs(142, 164).addBox(-4F, 0F, 0F, 8F, 7F, 9F), PartPose.offset(0F, 39F, 6F));
        root.addOrReplaceChild("magazinetop", CubeListBuilder.create().texOffs(440, 0).addBox(-5F, 0F, 0F, 10F, 11F, 26F), PartPose.offset(0F, 7F, 13F));
        root.addOrReplaceChild("magazinetoptrim", CubeListBuilder.create().texOffs(466, 38).addBox(-5F, 0F, 0F, 10F, 11F, 13F), PartPose.offset(0F, 7F, 0F));
        root.addOrReplaceChild("magazinemid", CubeListBuilder.create().texOffs(201, 0).addBox(-6F, 0F, 0F, 12F, 13F, 28F), PartPose.offset(0F, 18F, 11F));
        root.addOrReplaceChild("bodytopfront", CubeListBuilder.create().texOffs(423, 84).addBox(-6F, 0F, 0F, 12F, 18F, 32F), PartPose.offset(0F, -14F, -32F));
        root.addOrReplaceChild("bodytoprear", CubeListBuilder.create().texOffs(411, 167).addBox(-6F, 0F, 0F, 12F, 14F, 38F), PartPose.offset(0F, -14F, 82F));
        root.addOrReplaceChild("bodymidtrim", CubeListBuilder.create().texOffs(366, 236).addBox(-6F, 0F, 0F, 12F, 14F, 5F), PartPose.offset(0F, -14F, 0F));
        root.addOrReplaceChild("bodymidangletrim", CubeListBuilder.create().texOffs(477, 233).addBox(-6F, 0F, -5F, 12F, 17F, 5F), PartPose.offsetAndRotation(0F, -14F, 5F, 0.6109F, 0F, 0F));
        root.addOrReplaceChild("bodylow", CubeListBuilder.create().texOffs(248, 100).addBox(-6F, 0F, 0F, 12F, 7F, 120F), PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("bodylowtrim", CubeListBuilder.create().texOffs(444, 245).addBox(-6F, 0F, 0F, 12F, 6F, 4F), PartPose.offset(0F, -6F, 5F));
        root.addOrReplaceChild("bodystocktrim", CubeListBuilder.create().texOffs(401, 240).addBox(-6F, 0F, 0F, 12F, 6F, 9F), PartPose.offset(0F, 7F, 93F));
        root.addOrReplaceChild("bodyfronttrim", CubeListBuilder.create().texOffs(0, 51).addBox(-6F, 0F, 0F, 12F, 5F, 11F), PartPose.offset(0F, 1.5F, -43F));
        root.addOrReplaceChild("pumpfrontback", CubeListBuilder.create().texOffs(288, 83).addBox(-5F, 0F, 0F, 12F, 22F, 26F), PartPose.offset(-1F, 11F, -76F));
        root.addOrReplaceChild("pumpbackback", CubeListBuilder.create().texOffs(142, 105).addBox(-5F, 0F, 0F, 12F, 16F, 24F), PartPose.offset(-1F, 17F, -50F));
        root.addOrReplaceChild("handle", CubeListBuilder.create().texOffs(260, 112).addBox(-6F, 0F, 0F, 12F, 7F, 108F), PartPose.offset(0F, -28F, -17F));
        root.addOrReplaceChild("handleanglefront", CubeListBuilder.create().texOffs(393, 0).addBox(-6F, 0F, 0F, 12F, 35F, 9F), PartPose.offsetAndRotation(0F, -28F, -24F, -0.5585F, 0F, 0F));
        root.addOrReplaceChild("handlefronttrim", CubeListBuilder.create().texOffs(317, 234).addBox(-6F, 0F, 0F, 12F, 14F, 7F), PartPose.offset(0F, -28F, -24F));
        root.addOrReplaceChild("handlerear", CubeListBuilder.create().texOffs(177, 146).addBox(-6F, 0F, 0F, 12F, 17F, 30F), PartPose.offsetAndRotation(0F, -28F, 91F, -1.1519F, 0F, 0F));
        root.addOrReplaceChild("sightright", CubeListBuilder.create().texOffs(0, 19).addBox(-6F, 0F, 0F, 3F, 3F, 24F), PartPose.offset(0F, -31F, 67F));
        root.addOrReplaceChild("sightleft", CubeListBuilder.create().texOffs(0, 19).addBox(3F, 0F, 0F, 3F, 3F, 24F), PartPose.offset(0F, -31F, 67F));
        root.addOrReplaceChild("barrelspacer", CubeListBuilder.create().texOffs(0, 69).addBox(-5.5F, 0F, 0F, 11F, 3F, 45F), PartPose.offset(0F, 1F, -109F));
        root.addOrReplaceChild("barrelholderrear", CubeListBuilder.create().texOffs(112, 86).addBox(-4.5F, 0F, 0F, 9F, 4F, 12F), PartPose.offset(0F, -11F, -46F));
        root.addOrReplaceChild("barrelholdermid", CubeListBuilder.create().texOffs(155, 85).addBox(-4.5F, 0F, 0F, 9F, 4F, 13F), PartPose.offset(0F, -11F, -92F));
        root.addOrReplaceChild("barrelholderfront", CubeListBuilder.create().texOffs(200, 88).addBox(-4.5F, 0F, 0F, 9F, 4F, 10F), PartPose.offset(0F, -11F, -107F));
        root.addOrReplaceChild("grenadelauncher", CubeListBuilder.create().texOffs(0, 105).addBox(-4.5F, 0F, 0F, 9F, 27F, 123F), PartPose.offset(0F, 4F, -112F));
        root.addOrReplaceChild("grenadebarrel", CubeListBuilder.create().texOffs(48, 57).addBox(-4F, 0F, 0F, 8F, 8F, 2F), PartPose.offset(0F, 8F, -114F));
        root.addOrReplaceChild("grateright", CubeListBuilder.create().texOffs(365, 3).addBox(-4.5F, 0F, 0F, 2F, 9F, 71F), PartPose.offsetAndRotation(0F, -7F, -107F, 0F, 0F, 0.0873F));
        root.addOrReplaceChild("grateleft", CubeListBuilder.create().texOffs(212, 3).addBox(2.5F, 0F, 0F, 2F, 9F, 71F), PartPose.offsetAndRotation(0F, -7F, -106F, 0F, 0F, -0.0873F));
        root.addOrReplaceChild("stock", CubeListBuilder.create().texOffs(146, 0).addBox(-4.5F, 0F, 0F, 9F, 43F, 18F), PartPose.offset(0F, -10F, 120F));
        root.addOrReplaceChild("trigger", CubeListBuilder.create().texOffs(65, 0).addBox(-4.5F, 0F, 0F, 9F, 18F, 31F), PartPose.offset(0F, 7F, 39F));
        root.addOrReplaceChild("griptrim", CubeListBuilder.create().texOffs(0, 179).addBox(-4.5F, 0F, 0F, 9F, 3F, 45F), PartPose.offset(0F, 7F, 70F));
        root.addOrReplaceChild("grip", CubeListBuilder.create().texOffs(0, 118).addBox(-4.5F, 0F, 0F, 9F, 20F, 40F), PartPose.offsetAndRotation(0F, 7F, 70F, -0.8727F, 0F, 0F));
        root.addOrReplaceChild("magazinelow", CubeListBuilder.create().texOffs(294, 132).addBox(-6F, 0F, 0F, 12F, 28F, 24F), PartPose.offset(0F, 31F, 15F));
        root.addOrReplaceChild("pumpfront", CubeListBuilder.create().texOffs(288, 83).addBox(-5F, 0F, 0F, 12F, 22F, 26F), PartPose.offset(-1F, 11F, -107F));
        root.addOrReplaceChild("pumpback", CubeListBuilder.create().texOffs(142, 105).addBox(-5F, 0F, 0F, 12F, 16F, 24F), PartPose.offset(-1F, 17F, -81F));
        root.addOrReplaceChild("barrel", CubeListBuilder.create().texOffs(289, 0).addBox(-3F, 0F, 0F, 6F, 6F, 67F), PartPose.offset(0F, -9F, -113F));
        root.addOrReplaceChild("counter", CubeListBuilder.create().texOffs(0, 0).addBox(-5.5F, 0F, 0F, 11F, 7F, 11F), PartPose.offset(0F, 8F, 16F));
        return LayerDefinition.create(mesh, 512, 256);
    }
}
