package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model pulseRifleGrenade.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class PulseRifleGrenadeModel {
    public static final String[] PARTS = {"cap", "base", "groove", "body"};

    private PulseRifleGrenadeModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("cap", CubeListBuilder.create().texOffs(40, 0).addBox(-4F, -3F, 0F, 4F, 4F, 4F), PartPose.offset(2F, 1F, 0F));
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(0, 20).addBox(-3F, -3F, 0F, 6F, 6F, 1F), PartPose.offset(0F, 0F, 19F));
        root.addOrReplaceChild("groove", CubeListBuilder.create().texOffs(40, 8).addBox(-2.5F, -2.5F, 0F, 5F, 5F, 1F), PartPose.offset(0F, 0F, 18F));
        root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, 0F, 6F, 6F, 14F), PartPose.offset(0F, 0F, 4F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
