package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model pulseRifleMagazine.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class PulseRifleMagazineModel {
    public static final String[] PARTS = {"magazinelow", "magazinebase"};

    private PulseRifleMagazineModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("magazinelow", CubeListBuilder.create().texOffs(0, 0).addBox(-6F, 0F, 0F, 12F, 6F, 24F), PartPose.offset(0F, 53F, 15F));
        root.addOrReplaceChild("magazinebase", CubeListBuilder.create().texOffs(0, 30).addBox(-6F, 0F, 0F, 10F, 53F, 15F), PartPose.offset(1F, 0F, 19.5F));
        return LayerDefinition.create(mesh, 256, 128);
    }
}
