package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model pulseRifle_counter0.mad (+1 more). Generated by scripts/techne2java.py; do not edit by hand. */
public final class PulseRifleCounterModel {
    public static final String[] PARTS = {"counterright0", "counterleft0", "r_counterleft1", "r_counterright1"};

    private PulseRifleCounterModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("counterright0", CubeListBuilder.create().texOffs(0, 0).addBox(-5.5F, 0F, 0F, 5F, 5F, 3F), PartPose.offsetAndRotation(0F, 9F, 21F, 0F, 3.1416F, 0F));
        root.addOrReplaceChild("counterleft0", CubeListBuilder.create().texOffs(0, 0).addBox(-5.5F, 0F, 0F, 5F, 5F, 3F), PartPose.offset(0F, 9F, 22F));
        root.addOrReplaceChild("r_counterleft1", CubeListBuilder.create().texOffs(0, 0).addBox(-5.5F, 0F, 0F, 5F, 5F, 3F), PartPose.offsetAndRotation(0F, 9F, 25F, 0F, 3.1416F, 0F));
        root.addOrReplaceChild("r_counterright1", CubeListBuilder.create().texOffs(0, 0).addBox(-5.5F, 0F, 0F, 5F, 5F, 3F), PartPose.offset(0F, 9F, 18F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
