package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model pulseRifle_flash0.mad (+4 more). Generated by scripts/techne2java.py; do not edit by hand. */
public final class PulseRifleFlashModel {
    public static final String[] PARTS = {"flash4", "flash3", "flash2", "flash1", "flash0", "f1_flash0", "f1_flash1", "f1_flash2", "f2_flash0", "f2_flash1", "f2_flash2", "f3_flash0", "f3_flash1", "f3_flash2", "f4_flash0", "f4_flash1", "f4_flash2"};

    private PulseRifleFlashModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("flash4", CubeListBuilder.create().texOffs(289, 0).addBox(-3F, 0F, 0F, 10F, 10F, 16F), PartPose.offset(-2F, -11F, -177F));
        root.addOrReplaceChild("flash3", CubeListBuilder.create().texOffs(218, 41).addBox(-4F, 0F, 0F, 20F, 20F, 12F), PartPose.offset(-6F, -16F, -161F));
        root.addOrReplaceChild("flash2", CubeListBuilder.create().texOffs(289, 28).addBox(-4F, 0F, 0F, 24F, 24F, 8F), PartPose.offset(-8F, -18F, -149F));
        root.addOrReplaceChild("flash1", CubeListBuilder.create().texOffs(218, 41).addBox(-4F, 0F, 0F, 20F, 20F, 12F), PartPose.offset(-6F, -16F, -141F));
        root.addOrReplaceChild("flash0", CubeListBuilder.create().texOffs(289, 0).addBox(-3F, 0F, 0F, 10F, 10F, 16F), PartPose.offset(-2F, -11F, -129F));
        root.addOrReplaceChild("f1_flash0", CubeListBuilder.create().texOffs(364, 0).addBox(-4.5F, -4.5F, 0F, 9F, 9F, 64F), PartPose.offsetAndRotation(0F, -6F, -177F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("f1_flash1", CubeListBuilder.create().texOffs(170, 0).addBox(-10.5F, -10.5F, 0F, 21F, 21F, 32F), PartPose.offsetAndRotation(0F, -6F, -161F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("f1_flash2", CubeListBuilder.create().texOffs(0, 0).addBox(-12F, -12F, 0F, 25F, 25F, 8F), PartPose.offsetAndRotation(-0.5F, -6.5F, -149F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("f2_flash0", CubeListBuilder.create().texOffs(364, 0).addBox(-4.5F, -4.5F, 0F, 9F, 9F, 64F), PartPose.offset(0F, -6F, -177F));
        root.addOrReplaceChild("f2_flash1", CubeListBuilder.create().texOffs(170, 0).addBox(-10.5F, -10.5F, 0F, 21F, 21F, 32F), PartPose.offset(0F, -6F, -161F));
        root.addOrReplaceChild("f2_flash2", CubeListBuilder.create().texOffs(0, 0).addBox(-12F, -12F, 0F, 25F, 25F, 8F), PartPose.offset(-0.5F, -6.5F, -149F));
        root.addOrReplaceChild("f3_flash0", CubeListBuilder.create().texOffs(364, 0).addBox(-4.5F, -4.5F, 0F, 7F, 7F, 64F), PartPose.offset(0F, -6F, -177F));
        root.addOrReplaceChild("f3_flash1", CubeListBuilder.create().texOffs(170, 0).addBox(-10.5F, -10.5F, 0F, 19F, 19F, 32F), PartPose.offset(0F, -6F, -161F));
        root.addOrReplaceChild("f3_flash2", CubeListBuilder.create().texOffs(0, 0).addBox(-12F, -12F, 0F, 23F, 23F, 8F), PartPose.offset(-0.5F, -6.5F, -149F));
        root.addOrReplaceChild("f4_flash0", CubeListBuilder.create().texOffs(364, 0).addBox(-4.5F, -4.5F, 0F, 7F, 7F, 64F), PartPose.offsetAndRotation(0F, -6F, -177F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("f4_flash1", CubeListBuilder.create().texOffs(170, 0).addBox(-10.5F, -10.5F, 0F, 19F, 19F, 32F), PartPose.offsetAndRotation(0F, -6F, -161F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("f4_flash2", CubeListBuilder.create().texOffs(0, 0).addBox(-12F, -12F, 0F, 23F, 23F, 8F), PartPose.offsetAndRotation(-0.5F, -6.5F, -149F, 0F, 0F, 0.7854F));
        return LayerDefinition.create(mesh, 512, 256);
    }
}
