package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model componentPulseRifleBarrel.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class RifleComponentBarrelModel {
    public static final String[] PARTS = {"barrel", "barrelspacer", "barrelholderrear", "barrelholdermid", "barrelholderfront", "grateright", "grateleft"};

    private RifleComponentBarrelModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("barrel", CubeListBuilder.create().texOffs(289, 0).addBox(-3F, 0F, 0F, 6F, 6F, 67F), PartPose.offset(0F, -9F, -37F));
        root.addOrReplaceChild("barrelspacer", CubeListBuilder.create().texOffs(0, 69).addBox(-5.5F, 0F, 0F, 11F, 3F, 45F), PartPose.offset(0F, 1F, -33F));
        root.addOrReplaceChild("barrelholderrear", CubeListBuilder.create().texOffs(112, 86).addBox(-4.5F, 0F, 0F, 9F, 4F, 12F), PartPose.offset(0F, -11F, 30F));
        root.addOrReplaceChild("barrelholdermid", CubeListBuilder.create().texOffs(155, 85).addBox(-4.5F, 0F, 0F, 9F, 4F, 13F), PartPose.offset(0F, -11F, -16F));
        root.addOrReplaceChild("barrelholderfront", CubeListBuilder.create().texOffs(200, 88).addBox(-4.5F, 0F, 0F, 9F, 4F, 10F), PartPose.offset(0F, -11F, -31F));
        root.addOrReplaceChild("grateright", CubeListBuilder.create().texOffs(365, 3).addBox(-4.5F, 0F, 0F, 2F, 9F, 71F), PartPose.offsetAndRotation(0F, -7F, -30F, 0F, 0F, 0.0873F));
        root.addOrReplaceChild("grateleft", CubeListBuilder.create().texOffs(212, 3).addBox(2.5F, 0F, 0F, 2F, 9F, 71F), PartPose.offsetAndRotation(0F, -7F, -30F, 0F, 0F, -0.0873F));
        return LayerDefinition.create(mesh, 512, 256);
    }
}
