package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model componentPulseRifleReciever.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class RifleComponentReceiverModel {
    public static final String[] PARTS = {"magazinetop", "magazinemid", "magazinelow"};

    private RifleComponentReceiverModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("magazinetop", CubeListBuilder.create().texOffs(440, 0).addBox(-5F, 0F, 0F, 10F, 11F, 26F), PartPose.offset(0F, -28F, -14F));
        root.addOrReplaceChild("magazinemid", CubeListBuilder.create().texOffs(201, 0).addBox(-6F, 0F, 0F, 12F, 13F, 28F), PartPose.offset(0F, -17F, -16F));
        root.addOrReplaceChild("magazinelow", CubeListBuilder.create().texOffs(294, 132).addBox(-6F, 0F, 0F, 12F, 28F, 24F), PartPose.offset(0F, -4F, -12F));
        return LayerDefinition.create(mesh, 512, 256);
    }
}
