package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model componentPulseRifleBolt.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class RifleComponentBoltModel {
    public static final String[] PARTS = {"bolt", "boltbody"};

    private RifleComponentBoltModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("bolt", CubeListBuilder.create().texOffs(265, 245).addBox(-10F, 0F, 0F, 20F, 5F, 5F), PartPose.offset(0F, 16F, 27F));
        root.addOrReplaceChild("boltbody", CubeListBuilder.create().texOffs(201, 136).addBox(-4.5F, 0F, 0F, 9F, 9F, 74F), PartPose.offset(0F, 14F, -34F));
        return LayerDefinition.create(mesh, 512, 256);
    }
}
