package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model componentPulseRifleTrigger.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class RifleComponentTriggerModel {
    public static final String[] PARTS = {"trigger", "grip"};

    private RifleComponentTriggerModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("trigger", CubeListBuilder.create().texOffs(65, 0).addBox(-4.5F, 0F, 0F, 9F, 18F, 31F), PartPose.offset(0F, -21F, -30F));
        root.addOrReplaceChild("grip", CubeListBuilder.create().texOffs(0, 118).addBox(-4.5F, 0F, 0F, 7F, 20F, 40F), PartPose.offsetAndRotation(1F, -21F, 1F, -0.8727F, 0F, 0F));
        return LayerDefinition.create(mesh, 512, 256);
    }
}
