package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model needleSanitizer.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class SanitizerModel {
    public static final String[] PARTS = {"bottom", "top", "middle"};

    private SanitizerModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("bottom", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 7F, -8F));
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 12F, 16F), PartPose.offset(-8F, -8F, -8F));
        root.addOrReplaceChild("middle", CubeListBuilder.create().texOffs(11, 23).addBox(0F, 0F, 0F, 16F, 3F, 5F), PartPose.offset(-8F, 4F, 3F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
