package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model genomeSequencer.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class SequencerModel {
    public static final String[] PARTS = {"lower", "base", "foot1", "foot2", "foot3", "foot4", "top", "dna1", "dna2", "dna3", "dna4", "dna5", "dna6", "dna7", "dna8", "dna9", "dna10"};

    private SequencerModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("lower", CubeListBuilder.create().texOffs(0, 10).addBox(0F, 0F, 0F, 16F, 4F, 15F), PartPose.offset(-8F, 2F, -7F));
        root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(0, 13).addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 6F, -8F));
        root.addOrReplaceChild("foot1", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(6F, 7F, -7F));
        root.addOrReplaceChild("foot2", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-7F, 7F, -7F));
        root.addOrReplaceChild("foot3", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-7F, 7F, 6F));
        root.addOrReplaceChild("foot4", CubeListBuilder.create().texOffs(0, 30).addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(6F, 7F, 6F));
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(0, 4).addBox(0F, 0F, 0F, 16F, 8F, 9F), PartPose.offset(-8F, -6F, -1F));
        root.addOrReplaceChild("dna1", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-7F, 0F, -6F));
        root.addOrReplaceChild("dna2", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-5F, 0F, -6F));
        root.addOrReplaceChild("dna3", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-3F, 0F, -6F));
        root.addOrReplaceChild("dna4", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-1F, 0F, -6F));
        root.addOrReplaceChild("dna5", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(1F, 0F, -6F));
        root.addOrReplaceChild("dna6", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-7F, 0F, -4F));
        root.addOrReplaceChild("dna7", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-5F, 0F, -4F));
        root.addOrReplaceChild("dna8", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-3F, 0F, -4F));
        root.addOrReplaceChild("dna9", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-1F, 0F, -4F));
        root.addOrReplaceChild("dna10", CubeListBuilder.create().texOffs(60, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(1F, 0F, -4F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
