package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model soniclocator.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class SoniclocatorModel {
    public static final String[] PARTS = {"shieldright", "shieldleft", "shieldfront", "shieldmiddle", "warningtrimleft", "warningtrimright", "warningtrimback", "thumper1", "thumper2", "thumper3", "basemiddle", "basetrimrightback", "basetrimleftback", "trimright", "trimleft", "trimback", "trimfront", "braceright", "braceleft", "bracerightback", "braceleftback", "panelfront", "monitor", "basebottom1", "basebottom2", "basebottom3", "basebottom4", "plugleft", "plugright", "plugback", "plugfront"};

    private SoniclocatorModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shieldright", CubeListBuilder.create().texOffs(1, 1).addBox(0F, 0F, 0F, 1F, 21F, 11F), PartPose.offsetAndRotation(5F, -39F, -8F, 0.148F, 0F, 0F));
        root.addOrReplaceChild("shieldleft", CubeListBuilder.create().texOffs(26, 1).addBox(0F, 0F, 0F, 1F, 21F, 11F), PartPose.offsetAndRotation(-6F, -39F, -8F, 0.148F, 0F, 0F));
        root.addOrReplaceChild("shieldfront", CubeListBuilder.create().texOffs(51, 1).addBox(0F, 0F, 0F, 10F, 20F, 1F), PartPose.offsetAndRotation(-5F, -39F, -8F, 0.148F, 0F, 0F));
        root.addOrReplaceChild("shieldmiddle", CubeListBuilder.create().texOffs(1, 34).addBox(0F, 0F, 0F, 14F, 3F, 13F), PartPose.offset(-7F, -20F, -6F));
        root.addOrReplaceChild("warningtrimleft", CubeListBuilder.create().texOffs(82, 75).addBox(0F, 0F, 0F, 2F, 2F, 12F), PartPose.offsetAndRotation(-8F, -5F, -5.5333F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("warningtrimright", CubeListBuilder.create().texOffs(82, 90).addBox(0F, 0F, 0F, 2F, 2F, 12F), PartPose.offsetAndRotation(8F, -5F, -5.5F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("warningtrimback", CubeListBuilder.create().texOffs(86, 35).addBox(0F, 0F, 0F, 14F, 2F, 2F), PartPose.offsetAndRotation(-7F, -3.5F, 6.5F, 0.7854F, 0F, 0F));
        root.addOrReplaceChild("thumper1", CubeListBuilder.create().texOffs(1, 75).addBox(0F, 0F, 0F, 3F, 42F, 10F), PartPose.offset(-4.5F, -42F, -4F));
        root.addOrReplaceChild("thumper2", CubeListBuilder.create().texOffs(28, 75).addBox(0F, 0F, 0F, 3F, 42F, 10F), PartPose.offset(-1.5F, -42F, -4F));
        root.addOrReplaceChild("thumper3", CubeListBuilder.create().texOffs(55, 75).addBox(0F, 0F, 0F, 3F, 42F, 10F), PartPose.offset(1.5F, -42F, -4F));
        root.addOrReplaceChild("basemiddle", CubeListBuilder.create().texOffs(1, 59).addBox(0F, 0F, 0F, 14F, 2F, 13F), PartPose.offset(-7F, 0F, -6F));
        root.addOrReplaceChild("basetrimrightback", CubeListBuilder.create().texOffs(66, 23).addBox(0F, 0F, 0F, 5F, 5F, 2F), PartPose.offsetAndRotation(5F, 5F, -0.5F, 0F, 0F, 0.6632F));
        root.addOrReplaceChild("basetrimleftback", CubeListBuilder.create().texOffs(71, 32).addBox(0F, 0F, 0F, 5F, 5F, 2F), PartPose.offsetAndRotation(-5F, 5F, -0.5F, 0F, 0F, 0.9076F));
        root.addOrReplaceChild("trimright", CubeListBuilder.create().texOffs(56, 59).addBox(0F, 0F, 0F, 1F, 2F, 13F), PartPose.offset(7F, -1F, -6F));
        root.addOrReplaceChild("trimleft", CubeListBuilder.create().texOffs(85, 59).addBox(0F, 0F, 0F, 1F, 2F, 13F), PartPose.offset(-8F, -1F, -6F));
        root.addOrReplaceChild("trimback", CubeListBuilder.create().texOffs(1, 55).addBox(0F, 0F, 0F, 16F, 2F, 1F), PartPose.offset(-8F, -1F, 7F));
        root.addOrReplaceChild("trimfront", CubeListBuilder.create().texOffs(1, 51).addBox(0F, 0F, 0F, 16F, 2F, 1F), PartPose.offset(-8F, -1F, -7F));
        root.addOrReplaceChild("braceright", CubeListBuilder.create().texOffs(74, 1).addBox(0F, 0F, 0F, 2F, 17F, 2F), PartPose.offset(5F, -17F, -6F));
        root.addOrReplaceChild("braceleft", CubeListBuilder.create().texOffs(83, 1).addBox(0F, 0F, 0F, 2F, 17F, 2F), PartPose.offset(-7F, -17F, -6F));
        root.addOrReplaceChild("bracerightback", CubeListBuilder.create().texOffs(92, 1).addBox(0F, 0F, 0F, 1F, 22F, 1F), PartPose.offsetAndRotation(5.5F, -18F, -6F, 0.6427F, 0F, 0F));
        root.addOrReplaceChild("braceleftback", CubeListBuilder.create().texOffs(97, 1).addBox(0F, 0F, 0F, 1F, 22F, 1F), PartPose.offsetAndRotation(-6.5F, -18F, -6F, 0.6427F, 0F, 0F));
        root.addOrReplaceChild("panelfront", CubeListBuilder.create().texOffs(82, 105).addBox(0F, 0F, 0F, 13F, 7F, 1F), PartPose.offsetAndRotation(-6.5F, -7F, -6F, -0.1396F, 0F, 0F));
        root.addOrReplaceChild("monitor", CubeListBuilder.create().texOffs(82, 115).addBox(0F, 0F, 0F, 15F, 10F, 2F), PartPose.offset(-7.5F, -17F, -8F));
        root.addOrReplaceChild("basebottom1", CubeListBuilder.create().texOffs(56, 41).addBox(-2F, 0F, -5F, 4F, 7F, 10F), PartPose.offset(0F, 1F, 0.5F));
        root.addOrReplaceChild("basebottom2", CubeListBuilder.create().texOffs(56, 41).addBox(-2F, 0F, -5F, 4F, 7F, 10F), PartPose.offsetAndRotation(0F, 1F, 0.5F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("basebottom3", CubeListBuilder.create().texOffs(56, 41).addBox(-2F, 0F, -5F, 4F, 7F, 10F), PartPose.offsetAndRotation(0F, 1F, 0.5F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("basebottom4", CubeListBuilder.create().texOffs(56, 41).addBox(-2F, 0F, -5F, 4F, 7F, 10F), PartPose.offsetAndRotation(0F, 1F, 0.5F, 0F, -0.7854F, 0F));
        root.addOrReplaceChild("plugleft", CubeListBuilder.create().texOffs(102, 1).addBox(0F, 0F, 0F, 1F, 4F, 4F), PartPose.offset(-8F, -2F, -2F));
        root.addOrReplaceChild("plugright", CubeListBuilder.create().texOffs(102, 1).addBox(0F, 0F, 0F, 1F, 4F, 4F), PartPose.offsetAndRotation(8F, -2F, 2F, 0F, 3.1416F, 0F));
        root.addOrReplaceChild("plugback", CubeListBuilder.create().texOffs(102, 1).addBox(0F, 0F, 0F, 1F, 4F, 4F), PartPose.offsetAndRotation(-2F, -2F, 8F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("plugfront", CubeListBuilder.create().texOffs(102, 1).addBox(0F, 0F, 0F, 1F, 4F, 4F), PartPose.offsetAndRotation(2F, -2F, -8F, 0F, -1.5708F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
