package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model voxBox.mad. Generated by scripts/techne2java.py; do not edit by hand. */
public final class VoxBoxModel {
    public static final String[] PARTS = {"voxbox"};

    private VoxBoxModel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("voxbox", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 16F, 16F), PartPose.offset(-8F, -8F, -8F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
