"""Converts Techne models (.mad/.tcn zips holding model.xml) into Java LayerDefinition factories.

Usage: python scripts/techne2java.py <model.mad> <ClassName> [--block]

--block applies the original Mad Science block loader's convention (rotation point Y minus 16; the renderer then draws it
around the block centre with a (-1, -1, 1) flip), so a BlockEntityRenderer can reproduce the original look exactly.
Writes src/main/java/io/github/scwunge/madscience/client/model/<ClassName>.java.
"""
import re
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/main/java/io/github/scwunge/madscience/client/model"


def floats(text):
    return [float(v) for v in text.split(",")]


def num(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    if s in ("-0", ""):
        s = "0"
    return s + "F"


def part_name(name, used):
    base = re.sub(r"[^a-z0-9_]", "_", name.strip().lower()) or "part"
    if base[0].isdigit():
        base = "p_" + base
    candidate, i = base, 2
    while candidate in used:
        candidate = f"{base}_{i}"
        i += 1
    used.add(candidate)
    return candidate


def convert(model_path, class_name, block, extra=()):
    """extra: (prefix, path) pairs merged into the same layer, their parts named prefix + "_" + part."""
    sources = [("", model_path)] + list(extra)
    used, lines, names = set(), [], []
    tex_w = tex_h = None
    for prefix, path in sources:
        with zipfile.ZipFile(path) as z:
            root = ET.fromstring(z.read("model.xml"))
        model = root.find("Models/Model")
        w, h = (int(float(v)) for v in model.find("TextureSize").text.split(","))
        if tex_w is None:
            tex_w, tex_h = w, h
        convert_shapes(model, prefix, block, used, lines, names)
    write_class(model_path, class_name, tex_w, tex_h, lines, names, len(sources))


def convert_shapes(model, prefix, block, used, lines, names):
    for shape in model.find("Geometry").iter("Shape"):
        name = part_name((prefix + "_" if prefix else "") + shape.get("name", "part"), used)
        names.append(name)
        offset = floats(shape.find("Offset").text)
        pos = floats(shape.find("Position").text)
        rot = floats(shape.find("Rotation").text)
        size = floats(shape.find("Size").text)
        u, v = (int(float(x)) for x in shape.find("TextureOffset").text.split(","))
        mirrored = shape.find("IsMirrored").text.strip().lower() == "true"
        if block:
            pos[1] -= 16
        cube = f"CubeListBuilder.create().texOffs({u}, {v})"
        if mirrored:
            cube += ".mirror()"
        cube += f".addBox({num(offset[0])}, {num(offset[1])}, {num(offset[2])}, {num(size[0])}, {num(size[1])}, {num(size[2])})"
        if any(r != 0 for r in rot):
            pose = (f"PartPose.offsetAndRotation({num(pos[0])}, {num(pos[1])}, {num(pos[2])}, "
                    f"{num(rot[0] * 3.141592653589793 / 180)}, {num(rot[1] * 3.141592653589793 / 180)}, {num(rot[2] * 3.141592653589793 / 180)})")
        else:
            pose = f"PartPose.offset({num(pos[0])}, {num(pos[1])}, {num(pos[2])})"
        lines.append(f'        root.addOrReplaceChild("{name}", {cube}, {pose});')


def write_class(model_path, class_name, tex_w, tex_h, lines, names, files):
    source = f"""package io.github.scwunge.madscience.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original model {Path(model_path).name}{f" (+{files - 1} more)" if files > 1 else ""}. Generated by scripts/techne2java.py; do not edit by hand. */
public final class {class_name} {{
    public static final String[] PARTS = {{{", ".join(f'"{n}"' for n in names)}}};

    private {class_name}() {{
    }}

    public static LayerDefinition create() {{
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
{chr(10).join(lines)}
        return LayerDefinition.create(mesh, {tex_w}, {tex_h});
    }}
}}
"""
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{class_name}.java").write_text(source, encoding="utf-8", newline="\n")
    print(f"{class_name}: {len(names)} parts, texture {tex_w}x{tex_h}")


if __name__ == "__main__":
    # extra models to merge: prefix=path
    merged = [tuple(a.split("=", 1)) for a in sys.argv[3:] if "=" in a]
    convert(sys.argv[1], sys.argv[2], "--block" in sys.argv[3:], merged)
